#!/bin/sh
set -e

EXIT_OK=0
EXIT_USAGE=1
EXIT_FAILURE=2
# EXIT_RETRY=3

usage() {
    cat << EOF
USAGE
    dnf plugin for thin-edge.io

    $0 <COMMAND> [MODULE_NAME] [--module-version [VERSION]] [--file [FILE]]

    $0 list
    $0 prepare
    $0 install <MODULE_NAME> [--module-version [VERSION]] [--file [FILE]]
    $0 remove <MODULE_NAME> [--module-version [VERSION]]
    $0 finalize
EOF
}

MODULE_NAME=
MODULE_VERSION=
FILE=

log() { echo "$@" >&2; }

if [ $# -lt 1 ]; then
    log "Invalid number of positional arguments"
    usage
    exit "$EXIT_USAGE"
fi

# argument parsing
while [ $# -gt 0 ]; do
  case "$1" in
    --module-version)
        MODULE_VERSION="$2"
        shift
        ;;
    --file)
        FILE="$2"
        shift
        ;;
    -h|--help)
        usage
        exit "$EXIT_USAGE"
        ;;
    --*|-*)
        log "Unknown option $1"
        exit "$EXIT_USAGE"
        ;;
    *)
        if [ -z "$COMMAND" ]; then
            COMMAND="$1"
        elif [ -z "$MODULE_NAME" ]; then
            MODULE_NAME="$1"
        fi
      ;;
  esac
  shift
done

case "$COMMAND" in
    prepare)
        dnf update -y
        ;;
    list)
        # tedge-rpm-plugin-0.0.0rc0 noarch {tedge-rpm-plugin} (Apache License 2.0) [installed]
        if ! command -V dnf >/dev/null 2>&1; then
            log "dnf is not installed"
            exit "$EXIT_USAGE"
        fi

        # Use rpm to get the package list as it is common to all rpm based package managers
        # Note: version does not include release information
        # Note: rpm output is not sorted!
        TMP_FILE="$(mktemp)"
        rpm -qa --qf "%{NAME}\t%{VERSION}-%{RELEASE}\n" > "$TMP_FILE"
        sort -V "$TMP_FILE"
        rm -f "$TMP_FILE"
        ;;
    install)
        if [ -n "$FILE" ]; then
            log "Installing from file: $FILE"
            # dnf requires the file to have an .rpm extension
            ln -sf "$FILE" "$FILE.rpm"
            dnf install -y "$FILE.rpm" || exit "$EXIT_FAILURE"
            rm -f "$FILE.rpm"
        else
            MODULE="$MODULE_NAME"
            if [ -n "$MODULE_VERSION" ] && [ "$MODULE_VERSION" != "latest" ]; then
                MODULE="${MODULE_NAME}-${MODULE_VERSION}"
            fi

            log "Installing: $MODULE"
            dnf install -y "$MODULE" || exit "$EXIT_FAILURE"
        fi
        ;;
    remove)
        # Removing
        dnf remove -y "$MODULE_NAME" || exit "$EXIT_FAILURE"
        ;;
    update-list)
        # Not supported, use remove install and remove instead
        exit "$EXIT_USAGE"
        ;;
    finalize)
        ;;
    *)
        log "Unsupported command: $COMMAND"
        exit 1
        ;;
esac

exit "$EXIT_OK"