#!/bin/sh
set -e

EXIT_OK=0
EXIT_USAGE=1
EXIT_FAILURE=2
# EXIT_RETRY=3

usage() {
    cat << EOF
USAGE
    dnf plugin for thin-edge.io

    $0 <COMMAND> [MODULE_NAME] [--module-version [VERSION]] [--file [FILE]]

    $0 list
    $0 prepare
    $0 install <MODULE_NAME> [--module-version [VERSION]] [--file [FILE]]
    $0 remove <MODULE_NAME> [--module-version [VERSION]]
    $0 finalize
EOF
}

MODULE_NAME=
MODULE_VERSION=
FILE=

log() { echo "$@" >&2; }

if [ $# -lt 1 ]; then
    log "Invalid number of positional arguments"
    usage
    exit "$EXIT_USAGE"
fi

# argument parsing
while [ $# -gt 0 ]; do
  case "$1" in
    --module-version)
        MODULE_VERSION="$2"
        shift
        ;;
    --file)
        FILE="$2"
        shift
        ;;
    -h|--help)
        usage
        exit "$EXIT_USAGE"
        ;;
    --*|-*)
        log "Unknown option $1"
        exit "$EXIT_USAGE"
        ;;
    *)
        if [ -z "$COMMAND" ]; then
            COMMAND="$1"
        elif [ -z "$MODULE_NAME" ]; then
            MODULE_NAME="$1"
        fi
      ;;
  esac
  shift
done

command_exists() {
    command -V "$1" >/dev/null 2>&1
}

# Detect the rpm package manager
get_package_manager() {
    package_manager=
    if command_exists dnf; then
        package_manager="dnf"
    elif command_exists microdnf; then
        package_manager="microdnf"
    elif command_exists zypper; then
        package_manager="zypper"
    fi
    echo "$package_manager"
}

PACKAGE_MANAGER="${PACKAGE_MANAGER:-}"
if [ -z "$PACKAGE_MANAGER" ]; then
    PACKAGE_MANAGER=$(get_package_manager)
fi

case "$COMMAND" in
    prepare)
        case "$PACKAGE_MANAGER" in
            zypper)
                zypper refresh
                ;;
            dnf)
                # Not all dnf version support check-update
                dnf check-update ||:
                ;;
            microdnf)
                # microdnf does not implement check-update
                ;;
        esac
        ;;
    list)
        if ! command_exists "$PACKAGE_MANAGER"; then
            log "A rpm compatible command could not be found. Tried dnf, microdnf, zypper" >&2
            exit "$EXIT_USAGE"
        fi

        if ! command_exists rpm; then
            log "A rpm command was not found! This is very unexpected" >&2
            exit "$EXIT_USAGE"
        fi

        # Use rpm to get the package list as it is common to all rpm based package managers
        # Note: version does not include release information
        # Note: rpm output is not sorted!
        TMP_FILE="$(mktemp)"
        rpm -qa --qf "%{NAME}\t%{VERSION}-%{RELEASE}\n" > "$TMP_FILE"
        sort -V "$TMP_FILE"
        rm -f "$TMP_FILE"
        ;;
    install)
        if [ -n "$FILE" ]; then
            log "Installing from file: $FILE"
            # dnf requires the file to have an .rpm extension
            ln -sf "$FILE" "$FILE.rpm"

            CODE=
            case "$PACKAGE_MANAGER" in
                microdnf)
                    # microdnf does not support installing from local files, so use rpm directly
                    if ! rpm -i "$FILE.rpm"; then
                        CODE="$EXIT_FAILURE"
                    fi
                    ;;
                *)
                    if ! $PACKAGE_MANAGER install -y "$FILE.rpm"; then
                        CODE="$EXIT_FAILURE"
                    fi
                    ;;
            esac

            rm -f "$FILE.rpm"

            if [ -n "$CODE" ]; then
                exit "$CODE"
            fi
        else
            MODULE="$MODULE_NAME"
            if [ -n "$MODULE_VERSION" ] && [ "$MODULE_VERSION" != "latest" ]; then
                MODULE="${MODULE_NAME}-${MODULE_VERSION}"
            fi

            log "Installing: $MODULE"
            $PACKAGE_MANAGER install -y "$MODULE" || exit "$EXIT_FAILURE"
        fi
        ;;
    remove)
        # Removing
        $PACKAGE_MANAGER remove -y "$MODULE_NAME" || exit "$EXIT_FAILURE"
        ;;
    update-list)
        # Not supported, use remove install and remove instead
        exit "$EXIT_USAGE"
        ;;
    finalize)
        ;;
    *)
        log "Unsupported command: $COMMAND"
        exit 1
        ;;
esac

exit "$EXIT_OK"